### ISSUE TITLE
Should we add a Pilot Profile page??

### ISSUE THREAD

**Issue by Rickcau** [snodgrass23/quadrivals#9]
This isn't an issue but rather a way to track a discussion around - Should we have a Pilot Profile Page that has a photo of the Pilot an brief summary for each?  It would be awesome if we could create some sort of TXT template and have pilots keep that update-to-date with a summary and their results.  We could read and populate using this or implement a data entry page for pilots to maintain their profile.

**Comment by snodgrass23** [comment]
yeah, I had planned to eventually add a page for that. We could store any new props in the current pilots array.

**Comment by Rickcau** [comment]
na
